# Generated by Django 4.2.20 on 2025-09-27 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='バンド名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'バンド',
                'verbose_name_plural': 'バンド一覧',
            },
        ),
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='タイマー名')),
                ('duration_minutes', models.IntegerField(default=15, verbose_name='時間（分）')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='順序')),
                ('manager1', models.CharField(blank=True, max_length=50, verbose_name='管理者1')),
                ('manager2', models.CharField(blank=True, max_length=50, verbose_name='管理者2')),
                ('manager3', models.CharField(blank=True, max_length=50, verbose_name='管理者3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timer_core.band', verbose_name='バンド')),
            ],
            options={
                'verbose_name': 'タイマー',
                'verbose_name_plural': 'タイマー一覧',
                'ordering': ['band', 'order'],
            },
        ),
    ]
